#

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# set_property PACKAGE_PIN G7 [get_ports {HD_CLICK_CS0_1V8}]
# set_property PACKAGE_PIN G5 [get_ports {HD_CLICK_CS1_AN_1V8}]
# set_property PACKAGE_PIN E8 [get_ports {HD_CLICK_INT_1V8}]
# set_property PACKAGE_PIN E6 [get_ports {HD_CLICK_MISO_1V8}]
# set_property PACKAGE_PIN E5 [get_ports {HD_CLICK_MOSI_1V8}]
# set_property PACKAGE_PIN G6 [get_ports {HD_CLICK_PWM_1V8}]
# set_property PACKAGE_PIN D8 [get_ports {HD_CLICK_RST_1V8}]
# set_property PACKAGE_PIN D7 [get_ports {HD_CLICK_RX_1V8}]
# set_property PACKAGE_PIN F6 [get_ports {HD_CLICK_SCK_1V8}]
# set_property PACKAGE_PIN F8 [get_ports {HD_CLICK_SCL_1V8}]
# set_property PACKAGE_PIN F7 [get_ports {HD_CLICK_SDA_1V8}]
# set_property PACKAGE_PIN D6 [get_ports {HD_CLICK_TX_1V8}]
# set_property PACKAGE_PIN C5 [get_ports {HD_DP_07_GC_N}]
# set_property PACKAGE_PIN D5 [get_ports {HD_DP_07_GC_P}]
# set_property PACKAGE_PIN C7 [get_ports {HD_DP_08_GC_N}]
# set_property PACKAGE_PIN C8 [get_ports {HD_DP_08_GC_P}]
# set_property PACKAGE_PIN A8 [get_ports {HD_GPIO_PB1}]
# set_property PACKAGE_PIN B9 [get_ports {HD_HSIO_SCL_1V8}]
# set_property PACKAGE_PIN A9 [get_ports {HD_HSIO_SDA_1V8}]
# set_property PACKAGE_PIN A6 [get_ports {HD_SENSOR_I2C_SCL}]
# set_property PACKAGE_PIN B7 [get_ports {HD_SENSOR_I2C_SDA}]
# set_property PACKAGE_PIN T2 [get_ports {HP_DP[01]}]
# set_property PACKAGE_PIN T3 [get_ports {HP_DP[01]}]
# set_property PACKAGE_PIN R3 [get_ports {HP_DP[02]}]
# set_property PACKAGE_PIN P3 [get_ports {HP_DP[02]}]
# set_property PACKAGE_PIN U1 [get_ports {HP_DP[03]}]
# set_property PACKAGE_PIN U2 [get_ports {HP_DP[03]}]
# set_property PACKAGE_PIN T4 [get_ports {HP_DP[04]}]
# set_property PACKAGE_PIN R4 [get_ports {HP_DP[04]}]
# set_property PACKAGE_PIN T1 [get_ports {HP_DP[05]}]
# set_property PACKAGE_PIN R1 [get_ports {HP_DP[05]}]
# set_property PACKAGE_PIN R5 [get_ports {HP_DP[06]}]
# set_property PACKAGE_PIN P5 [get_ports {HP_DP[06]}]
# set_property PACKAGE_PIN P1 [get_ports {HP_DP[07]}]
# set_property PACKAGE_PIN N2 [get_ports {HP_DP[07]}]
# set_property PACKAGE_PIN N4 [get_ports {HP_DP[08]}]
# set_property PACKAGE_PIN N5 [get_ports {HP_DP[08]}]
# set_property PACKAGE_PIN M1 [get_ports {HP_DP[09]}]
# set_property PACKAGE_PIN M2 [get_ports {HP_DP[09]}]
# set_property PACKAGE_PIN M4 [get_ports {HP_DP[10]}]
# set_property PACKAGE_PIN M5 [get_ports {HP_DP[10]}]
# set_property PACKAGE_PIN B1 [get_ports {HP_DP[11]}]
# set_property PACKAGE_PIN B2 [get_ports {HP_DP[11]}]
# set_property PACKAGE_PIN L1 [get_ports {HP_DP[11]}]
# set_property PACKAGE_PIN L2 [get_ports {HP_DP[11]}]
# set_property PACKAGE_PIN A3 [get_ports {HP_DP[12]}]
# set_property PACKAGE_PIN A4 [get_ports {HP_DP[12]}]
# set_property PACKAGE_PIN L3 [get_ports {HP_DP[12]}]
# set_property PACKAGE_PIN L4 [get_ports {HP_DP[12]}]
# set_property PACKAGE_PIN J2 [get_ports {HP_DP[13]}]
# set_property PACKAGE_PIN J3 [get_ports {HP_DP[13]}]
# set_property PACKAGE_PIN K3 [get_ports {HP_DP[14]}]
# set_property PACKAGE_PIN K4 [get_ports {HP_DP[14]}]
# set_property PACKAGE_PIN J1 [get_ports {HP_DP[15]}]
# set_property PACKAGE_PIN K1 [get_ports {HP_DP[15]}]
# set_property PACKAGE_PIN H5 [get_ports {HP_DP[16]}]
# set_property PACKAGE_PIN J5 [get_ports {HP_DP[16]}]
# set_property PACKAGE_PIN G2 [get_ports {HP_DP[17]}]
# set_property PACKAGE_PIN H2 [get_ports {HP_DP[17]}]
# set_property PACKAGE_PIN G4 [get_ports {HP_DP[18]}]
# set_property PACKAGE_PIN H4 [get_ports {HP_DP[18]}]
# set_property PACKAGE_PIN F1 [get_ports {HP_DP[19]}]
# set_property PACKAGE_PIN G1 [get_ports {HP_DP[19]}]
# set_property PACKAGE_PIN E3 [get_ports {HP_DP[20]}]
# set_property PACKAGE_PIN E4 [get_ports {HP_DP[20]}]
# set_property PACKAGE_PIN D1 [get_ports {HP_DP[21]}]
# set_property PACKAGE_PIN E1 [get_ports {HP_DP[21]}]
# set_property PACKAGE_PIN C3 [get_ports {HP_DP[22]}]
# set_property PACKAGE_PIN D3 [get_ports {HP_DP[22]}]
# set_property PACKAGE_PIN F2 [get_ports {HP_DP[23]}]
# set_property PACKAGE_PIN F3 [get_ports {HP_DP[23]}]
# set_property PACKAGE_PIN C2 [get_ports {HP_DP[24]}]
# set_property PACKAGE_PIN D2 [get_ports {HP_DP[24]}]
# set_property PACKAGE_PIN N3 [get_ports {HP_SE[01]}]
# set_property PACKAGE_PIN H3 [get_ports {HP_SE[02]}]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_CS0_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_CS1_AN_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_INT_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_MISO_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_MOSI_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_PWM_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_RST_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_RX_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_SCK_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_SCL_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_SDA_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_CLICK_TX_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_DP_07_GC_N}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_DP_07_GC_P}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_DP_08_GC_N}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_DP_08_GC_P}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_GPIO_PB1}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_HSIO_SCL_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_HSIO_SDA_1V8}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_SENSOR_I2C_SCL}]
# set_property IOSTANDARD LVCMOS18 [get_ports {HD_SENSOR_I2C_SDA}]
# set_property IOSTANDARD LVCMOS12 [get_ports {HP_DP[*]}]
# set_property IOSTANDARD LVCMOS12 [get_ports {HP_SE[*]}]

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
set_property PACKAGE_PIN B5 [get_ports HD_GPIO_RGB1_B]
set_property PACKAGE_PIN B6 [get_ports HD_GPIO_RGB1_G]
set_property PACKAGE_PIN A7 [get_ports HD_GPIO_RGB1_R]
set_property PACKAGE_PIN F4 [get_ports HP_GPIO_RGB2_B]
set_property PACKAGE_PIN A2 [get_ports HP_GPIO_RGB2_G]
set_property PACKAGE_PIN B4 [get_ports HP_GPIO_RGB2_R]

set_property IOSTANDARD LVCMOS18 [get_ports HD_GPIO_RGB1_B]
set_property IOSTANDARD LVCMOS18 [get_ports HD_GPIO_RGB1_G]
set_property IOSTANDARD LVCMOS18 [get_ports HD_GPIO_RGB1_R]
set_property IOSTANDARD LVCMOS12 [get_ports HP_GPIO_RGB2_B]
set_property IOSTANDARD LVCMOS12 [get_ports HP_GPIO_RGB2_G]
set_property IOSTANDARD LVCMOS12 [get_ports HP_GPIO_RGB2_R]

